<?php
// Diccionario actualizado con las nuevas traducciones para Almuerzo/Cena
$texts = [
    'es' => [
        'confirmacion' => 'Confirmación de Evento',
        'estimado' => 'Estimado/a',
        'instruccion' => 'complete los detalles operativos y legales para su evento.',
        'sec1_titulo' => '1. Información de Facturación y Contrato',
        'razon_social' => 'Razón Social (Empresa o Persona natural):',
        'rep_legal' => 'Nombre del Representante Legal:',
        'id_fiscal' => 'RUC / Cédula de Identidad:',
        'dir_fiscal' => 'Dirección Fiscal:',
        'tel_contacto' => 'Teléfono de Contacto:',
        'correo_fact' => 'Correo electrónico para envío de factura:',
        'firma_nombre' => 'Nombre de quien firma el contrato:',
        'firma_id' => 'Identificación de quien firma el contrato:',
        'encargado_dia' => 'Persona encargada el día del evento:',
        'nombre_encargado' => 'Nombre del encargado:',
        'cel_encargado' => 'Número celular del encargado:',
        'sec2_titulo' => '2. Horarios y Equipos Audiovisuales',
        'h_inicio' => 'Hora de Inicio:',
        'h_fin' => 'Hora de Finalización:',
        'equipos' => 'Equipos Audiovisuales Solicitados:',
        'sec3_titulo' => '3. Selección de Menú',
        'sec4_titulo' => '4. Montaje y Estilo del Salón',
        'manteleria' => 'Color de Mantelería:',
        'servilletas' => 'Color de Servilletas:',
        'sec5_titulo' => '5. Observaciones, Alergias y Logística',
        'obs_cocina' => '⚠️ Observaciones y Restricciones Alimenticias (Cocina):',
        'logistica' => '📝 Logística de Proveedores y Montaje:',
        'planimetria' => 'Subir Croquis o Planimetría (Opcional):',
        'btn_enviar' => 'CONFIRMAR TODOS LOS DETALLES DEL EVENTO',

        // --- Traducciones para Menú Cóctel ---
        'menu_plan_coctel_title' => 'Menú Plan Cóctel:',
        'menu_plan_coctel_desc' => 'Seleccione 6 bocaditos. Use el visor a la derecha para ver la referencia de cada uno.',
        'vista_previa' => 'Vista Previa',
        'visor_instruccion' => 'Pase el mouse sobre un bocado',
        'seleccionados' => 'Seleccionados',
        'cat_bocados_salados' => 'BOCADOS SALADOS',
        'cat_vegetariano_/_vegano' => 'VEGETARIANO / VEGANO',
        'cat_mariscos_y_pescados' => 'MARISCOS Y PESCADOS',
        'cat_bocaditos_dulces' => 'BOCADITOS DULCES',

        // --- Traducciones para Menú Desayunos ---
        'placeholder_visor' => 'Pasa el mouse sobre un menú para ver la referencia visual',
        'desayuno_saludable' => 'Saludable',
        'desayuno_americano' => 'Americano',
        'desayuno_especial' => 'Especial',
        'desayuno_ecuatoriano' => 'Ecuatoriano',

        // --- Traducciones para Menú Seminario (Interfaz) ---
        'seminario_title' => 'Plan Seminario:',
        'seminario_desc' => 'Seleccione la modalidad (Full Day o Half Day). Ambos planes incluyen Almuerzo Ejecutivo (Elija 1 Entrada, 1 Fuerte y 1 Postre).',
        'full_day' => 'FULL DAY (8 Horas)',
        'half_day' => 'HALF DAY (6 Horas)',
        'coffee_am' => 'Coffee Break AM (2 bocaditos)',
        'coffee_pm' => 'Coffee Break PM (2 bocaditos)',
        'almuerzo_3' => 'Almuerzo Ejecutivo (3 tiempos)',
        'agua_ilimitada' => 'Agua filtrada ilimitada',
        'sel_almuerzo' => 'Selección de Almuerzo Ejecutivo',
        'instruccion_almuerzo' => 'Por favor, seleccione una opción de cada tiempo.',
        'entrada_titulo' => '1. ENTRADAS (Elija 1)',
        'fuerte_titulo' => '2. PLATOS FUERTES (Elija 1)',
        'postre_titulo' => '3. POSTRES (Elija 1)',
        'visor_seminario' => 'Pase el ratón sobre un plato',

        // --- Nuevas traducciones para Coffee Break ---
        'Menú Coffee Break:' => 'Menú Coffee Break:',
        'Seleccione el horario y elija exactamente' => 'Seleccione el horario y elija exactamente',
        '2 bocaditos por persona.' => '2 bocaditos por persona.',
        'Mañana' => 'Mañana',
        'Tarde' => 'Tarde',
        'No hay bocaditos disponibles en el menú.' => 'No hay bocaditos disponibles en el menú.',
        'de 2' => 'de 2',

        // --- Nuevas traducciones para Almuerzo/Cena ---
        'menu_almuerzo_title' => 'Menú Almuerzo / Cena:',
        'menu_almuerzo_desc' => 'Seleccione el plan deseado y elija un plato por cada tiempo disponible según su plan.',
        'menu_2_tiempos' => 'Menú 2 Tiempos',
        'menu_2_sub' => 'Fuerte + Postre',
        'menu_3_tiempos' => 'Menú 3 Tiempos',
        'menu_3_sub' => 'Entrada + Fuerte + Postre',
        'menu_4_tiempos' => 'Menú 4 Tiempos',
        'menu_4_sub' => 'Entrada + Sorbet + Fuerte + Postre',
        'entradas_title' => 'ENTRADAS / CEVICHES',
        'platos_fuertes_title' => 'PLATOS FUERTES',
        'postres_title' => 'POSTRES',
        'sorbet_title' => 'SORBET DE LIMÓN',
        'sorbet_limon' => 'Sorbet de Limón',
        'instruccion_preview' => 'Pase el mouse sobre un plato para verlo aquí',
        'alt_preview' => 'Vista previa del plato',
        'select_plate' => 'Seleccione un plato',
        'total_selected' => 'Total seleccionados',
        'No hay opciones configuradas.' => 'No hay opciones configuradas.',

        // Ítems de la base de datos (Llaves exactas)
        'Jugo de apio, perejil y naranja o jugo de' => 'Jugo de apio, perejil y naranja o jugo de',
        'fruta de estación (2 variedades)' => 'fruta de estación (2 variedades)',
        'Jugo de fruta de estación (2 variedades)' => 'Jugo de fruta de estación (2 variedades)',
        'Frutas tropicales de estación' => 'Frutas tropicales de estación',
        'Avena bircher (yogur natural, avena, frutos' => 'Avena bircher (yogur natural, avena, frutos',
        'secos, manzana y plátano)' => 'secos, manzana y plátano)',
        'Tostadas de pan de molde integral' => 'Tostadas de pan de molde integral',
        'Plato de queso fresco y jamón de pavo' => 'Plato de queso fresco y jamón de pavo',
        'Huevos pasados (10 minutos)' => 'Huevos pasados (10 minutos)',
        'Omelette de queso y champiñones,' => 'Omelette de queso y champiñones,',
        'acompañado con fetas de jamón, tocino y' => 'acompañado con fetas de jamón, tocino y',
        'salchicha' => 'salchicha',
        'Cesta de panes surtidos' => 'Cesta de panes surtidos',
        'Mermelada y mantequilla para untar' => 'Mermelada y mantequilla para untar',
        'Avena bircher (con yogur natural, avena,' => 'Avena bircher (con yogur natural, avena,',
        'Servicio de café, aromáticas y leche' => 'Servicio de café, aromáticas y leche',
        'Panqueques con fruta tropical' => 'Panqueques con fruta tropical',
        'Salchicha y tocino' => 'Salchicha y tocino',
        'Avena bircher' => 'Avena bircher',
        'Opción 1' => 'Opción 1',
        'Tigrillo con queso criollo, huevo frito y' => 'Tigrillo con queso criollo, huevo frito y',
        'chicharrón crocante' => 'chicharrón crocante',
        'Opción 2' => 'Opción 2',
        'Mote con chicharrón crocante y maduro frito' => 'Mote con chicharrón crocante y maduro frito',
    ],
    'en' => [
        'confirmacion' => 'Event Confirmation',
        'estimado' => 'Dear',
        'instruccion' => 'please complete the operational and legal details for your event.',
        'sec1_titulo' => '1. Billing and Contract Information',
        'razon_social' => 'Business Name (Company or Individual):',
        'rep_legal' => 'Legal Representative Name:',
        'id_fiscal' => 'Tax ID / ID Number:',
        'dir_fiscal' => 'Billing Address:',
        'tel_contacto' => 'Contact Phone:',
        'correo_fact' => 'Email for Invoicing:',
        'firma_nombre' => 'Contract Signatory Name:',
        'firma_id' => 'Contract Signatory ID:',
        'encargado_dia' => 'Person in charge on the day of the event:',
        'nombre_encargado' => 'Contact person name:',
        'cel_encargado' => 'Contact person cell phone:',
        'sec2_titulo' => '2. Schedule and Audiovisual Equipment',
        'h_inicio' => 'Start Time:',
        'h_fin' => 'End Time:',
        'equipos' => 'Requested Audiovisual Equipment:',
        'sec3_titulo' => '3. Menu Selection',
        'sec4_titulo' => '4. Setup and Room Style',
        'manteleria' => 'Tablecloth Color:',
        'servilletas' => 'Napkin Color:',
        'sec5_titulo' => '5. Observations, Allergies, and Logistics',
        'obs_cocina' => '⚠️ Dietary Restrictions and Observations (Kitchen):',
        'logistica' => '📝 Vendor Logistics and Setup:',
        'planimetria' => 'Upload Layout or Floor Plan (Optional):',
        'btn_enviar' => 'CONFIRM ALL EVENT DETAILS',

        // --- Traducciones para Menú Cóctel ---
        'menu_plan_coctel_title' => 'Cocktail Plan Menu:',
        'menu_plan_coctel_desc' => 'Select 6 appetizers. Use the viewer on the right to see the reference for each one.',
        'vista_previa' => 'Preview',
        'visor_instruccion' => 'Hover over an appetizer',
        'seleccionados' => 'Selected',
        'cat_bocados_salados' => 'SAVORY SNACKS',
        'cat_vegetariano_/_vegano' => 'VEGETARIAN / VEGAN',
        'cat_mariscos_y_pescados' => 'SEAFOOD & FISH',
        'cat_bocaditos_dulces' => 'SWEET TREATS',

        // --- Traducciones para Menú Desayunos ---
        'placeholder_visor' => 'Hover over a menu to see the visual reference',
        'desayuno_saludable' => 'Healthy',
        'desayuno_americano' => 'American',
        'desayuno_especial' => 'Special',
        'desayuno_ecuatoriano' => 'Ecuadorian',

        // --- Traducciones para Menú Seminario (Interfaz) ---
        'seminario_title' => 'Seminar Plan:',
        'seminario_desc' => 'Select the modality (Full Day or Half Day). Both plans include Executive Lunch (Choose 1 Starter, 1 Main Course and 1 Dessert).',
        'full_day' => 'FULL DAY (8 Hours)',
        'half_day' => 'HALF DAY (6 Hours)',
        'coffee_am' => 'AM Coffee Break (2 snacks)',
        'coffee_pm' => 'PM Coffee Break (2 snacks)',
        'almuerzo_3' => 'Executive Lunch (3 courses)',
        'agua_ilimitada' => 'Unlimited filtered water',
        'sel_almuerzo' => 'Executive Lunch Selection',
        'instruccion_almuerzo' => 'Please select one option for each course.',
        'entrada_titulo' => '1. STARTERS (Choose 1)',
        'fuerte_titulo' => '2. MAIN COURSES (Choose 1)',
        'postre_titulo' => '3. DESSERTS (Choose 1)',
        'visor_seminario' => 'Hover over a dish',

        // --- Nuevas traducciones para Coffee Break ---
        'Menú Coffee Break:' => 'Coffee Break Menu:',
        'Seleccione el horario y elija exactamente' => 'Select the time slot and choose exactly',
        '2 bocaditos por persona.' => '2 snacks per person.',
        'Mañana' => 'Morning',
        'Tarde' => 'Afternoon',
        'No hay bocaditos disponibles en el menú.' => 'No snacks available in the menu.',
        'de 2' => 'of 2',

        // --- Nuevas traducciones para Almuerzo/Cena ---
        'menu_almuerzo_title' => 'Lunch / Dinner Menu:',
        'menu_almuerzo_desc' => 'Select the desired plan and choose one dish for each available course according to your plan.',
        'menu_2_tiempos' => '2-Course Menu',
        'menu_2_sub' => 'Main + Dessert',
        'menu_3_tiempos' => '3-Course Menu',
        'menu_3_sub' => 'Starter + Main + Dessert',
        'menu_4_tiempos' => '4-Course Menu',
        'menu_4_sub' => 'Starter + Sorbet + Main + Dessert',
        'entradas_title' => 'STARTERS / CEVICHES',
        'platos_fuertes_title' => 'MAIN COURSES',
        'postres_title' => 'DESSERTS',
        'sorbet_title' => 'LEMON SORBET',
        'sorbet_limon' => 'Lemon Sorbet',
        'instruccion_preview' => 'Hover over a dish to see it here',
        'alt_preview' => 'Dish preview',
        'select_plate' => 'Select a dish',
        'total_selected' => 'Total selected',
        'No hay opciones configuradas.' => 'No options configured.',

        // Ítems de la base de datos (Traducciones)
        'Jugo de apio, perejil y naranja o jugo de' => 'Celery, parsley and orange juice or',
        'fruta de estación (2 variedades)' => 'seasonal fruit juice (2 varieties)',
        'Jugo de fruta de estación (2 variedades)' => 'Seasonal fruit juice (2 varieties)',
        'Frutas tropicales de estación' => 'Seasonal tropical fruits',
        'Avena bircher (yogur natural, avena, frutos' => 'Bircher muesli (natural yogurt, oats, nuts,',
        'secos, manzana y plátano)' => 'dried fruits, apple and banana)',
        'Tostadas de pan de molde integral' => 'Whole wheat toast',
        'Plato de queso fresco y jamón de pavo' => 'Fresh cheese and turkey ham platter',
        'Huevos pasados (10 minutos)' => 'Soft-boiled eggs (10 minutes)',
        'Omelette de queso y champiñones,' => 'Cheese and mushroom omelette,',
        'acompañado con fetas de jamón, tocino y' => 'served with slices of ham, bacon and',
        'salchicha' => 'sausage',
        'Cesta de panes surtidos' => 'Assorted bread basket',
        'Mermelada y mantequilla para untar' => 'Jam and butter for spreading',
        'Avena bircher (con yogur natural, avena,' => 'Bircher muesli (with natural yogurt, oats,',
        'Servicio de café, aromáticas y leche' => 'Coffee, herbal tea and milk service',
        'Panqueques con fruta tropical' => 'Pancakes with tropical fruit',
        'Salchicha y tocino' => 'Sausage and bacon',
        'Avena bircher' => 'Bircher muesli',
        'Opción 1' => 'Option 1',
        'Tigrillo con queso criollo, huevo frito y' => 'Tigrillo (mashed plantain) with Creole cheese, fried egg and',
        'chicharrón crocante' => 'crispy pork rind',
        'Opción 2' => 'Option 2',
        'Mote con chicharrón crocante y maduro frito' => 'Mote (hominy) with crispy pork rind and fried sweet plantain',
    ]
];
?>